### ISSUE TITLE
figures gather/spread not rendering online

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/dwc-in-R#14]
see: https://inbo.github.io/dwc-in-R/dplyr.html#9_reshape_data

**Comment by damianooldoni** [comment]
Thanks, @stijnvanhoey for noticing it. 
It is still quite strange. I downloaded the repository (master) and opened the `html` file and the pictures are shown correctly.

**Comment by stijnvanhoey** [comment]
`![spread](../docs/static/images/spread_data_R.png)` should be
`![spread](./static/images/spread_data_R.png)`

As all files in src will be copied to docs and relative path will be the same in both towards the static folder containing the images (mimic of src/static/images to docs/static/images.

**Comment by damianooldoni** [comment]
Ok. I apply the changes in the new branch [render-dplyr.Rmd-exercises-solutions](https://github.com/inbo/dwc-in-R/tree/render-dplyr.Rmd-exercises-solutions)

**Comment by damianooldoni** [comment]
See commit 51bcaf2d8dca1b029a1c59bf837c7b9f693b8e01

**Comment by peterdesmet** [comment]
Nice, closing.
