### ISSUE TITLE
remove slides 1->7 or 1->9  in the tidy presentation

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/dwc-in-R#6]
As we collect all material in a collective workshop, we should exclude the lifewatch intro at that moment.

**Comment by stijnvanhoey** [comment]
+ slide 10 adapt to good `data` practices
+ slide 8 split in two: 8.1. figure only; 8.2 figure + tools,tools,..

**Comment by peterdesmet** [comment]
Can be done by you, after #8 is accepted, in src/tidy.html

**Comment by stijnvanhoey** [comment]
Fixed by #12 merge
